### ISSUE TITLE
h5 model and weight file

### ISSUE THREAD

**Issue by tkwoo** [nyoki-mtl/keras-facenet#1]
I followed the notebook files.
But, there is some problem for creating keras model file from tf ckpt.
Svm and image results are weird although It successfully created the h5 file.
I think that has problem in converting process for my case.
Can you upload you keras model file?

my env : tf1.3, keras2.1.2, python2.7 or 3.6

**Comment by nyoki-mtl** [comment]
Sorry for the late reply.
I uploaded keras model files.
https://drive.google.com/open?id=1pwQ3H4aJ8a6yyJHZkTwtjcL4wYWQb7bn

My Environments:
Ubuntu16.04 or Windows10
python3.6.2
tensorflow: 1.3.0
keras: 2.1.2
