### ISSUE TITLE
Get error with webcam demo

### ISSUE THREAD

**Issue by Stephenfang51** [nyoki-mtl/keras-facenet#14]
Sir, 

when I run the f.train(). it shows below
How can I solve it?

 ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-50-770cb541f283> in <module>
----> 1 f.train()

<ipython-input-47-720c27c39f20> in train(self)
     73             embs.append(embs_)
     74 
---> 75         embs = np.concatenate(embs)
     76         le = LabelEncoder().fit(labels)
     77         y = le.transform(labels)

ValueError: need at least one array to concatenate

**Comment by abhishekgupte94** [comment]
The problem is that the embs array is empty. Load it with face embeddings
